#!/bin/sh
set -e

echo "$CRON_SCHEDULE sh /app/backup.sh" > /etc/crontabs/root


if [ -z $MYSQL_DATABASES ]; then
    MYSQL_DATABASES="All dbs"
fi

echo "Mysql server: $MYSQL_SERVER"
echo "Mysql databases: $MYSQL_DATABASES"
echo "Mysql user: $MYSQL_USER"
echo "Mysql password: $(echo $MYSQL_PASSWORD | cut -c -4)****"
echo "Mysql retention days: $BAK_RETENTION"
echo "Cron: $CRON_SCHEDULE"
echo ""

mysql --host=$MYSQL_SERVER --user=$MYSQL_USER --password=$MYSQL_PASSWORD -e "SHOW DATABASES;" > /dev/null 2>&1 || echo "Cannot connect with dbserver" && exit 1

crond -f -l 8
