#!/bin/bash
set -euo pipefail

env > /etc/environment
echo "$CRON_SCHEDULE root sh /app/backup.sh > /proc/1/fd/1 2>/proc/1/fd/2" > /etc/cron.d/cronfile
echo "" >> /etc/cron.d/cronfile

echo "Mysql server: $MYSQL_SERVER"
echo "Mysql user: $MYSQL_USER"
echo "Mysql password: $(echo $MYSQL_PASSWORD | cut -c -4)****"
echo "Mysql retention days: $BAK_RETENTION"
echo "Cron set: $CRON_SCHEDULE"
echo ""

/usr/sbin/cron -f 8
